
jobs:
  - name: test
    plan:
      - {put: version, params: {bump: patch}}
      - {get: repo, trigger: true}
      - task: test
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: node, tag: "8" }
          inputs:
            - name: repo
            - name: version
          run:
            path: /bin/bash
            args:
              - -c
              - |
                set -e
                echo "VERSION: $(cat ./version/version)"
                cd repo
                npm install
                npm test
      - put: test-app-image
        params:
          build: ./repo
          tag_file: ./version/version
        get_params: {skip_download: true}

resources:
  - name: test-app-image
    type: docker-image
    source:
      repository: gcr.io/sports-leap-prod/kirmanie-test-app
      username: _json_key
      password: ((common-secrets.leap-cluster-admin))

  - name: version
    type: semver
    source:
      driver: gcs
      bucket: leap-artifact-versions
      key: kirmanie-test-app
      json_key: ((common-secrets.leap-cluster-admin))
  - name: repo
    type: git
    icon: github-circle
    source:
      uri: https://github.com/kirmanie/test-app.git
      branch: master


